# Generated by Django 2.2.17 on 2021-03-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordersapp", "0002_auto_20210325_1705"),
        ("ordersapp", "0002_auto_20210318_1843"),
    ]

    operations = []
